### PR TITLE
GitHub Actions workflow for validation

### PR DESCRIPTION
**Pull request by nathanweeks**
Automate legumeinfo/datastore-specifications [validate](https://github.com/legumeinfo/datastore-specifications/blob/main/validate) script in a GitHub Actions workflow.

### CODE REVIEW

**Comment by sammyjava** [comment]
This is cool. Right now we have over 200 READMEs that fail validation, so I'll hold off on pondering this until that chore is done sometime next week (it's not actually as tedious as it sounds).

**Comment by sammyjava** [comment]
Although actually it seems to work fine, I didn't realize it had already ran the YAML and validations as part of the "push". I think if this is how it usually works with commits, whenever I finish up validating, you can merge the main branch into this branch and it should automatically rerun those validations and come up rosy. Next week.

**Comment by nathanweeks** [comment]
Manually rerunning the GitHub Actions workflow via the web UI, the main branch is looking better---almost there (https://github.com/legumeinfo/datastore-metadata/runs/4721322026). If you think this workflow is good-enough as-is, it could probably be merged soon-ish (though double check the glob patterns for correctness; they might need adjustment now or in the future).

**Comment by sammyjava** [comment]
I think it's good, but I still have about 50 READMEs to update, and I don't want to have to update ALL of them before I can get a commit through. So let's wait until I'm done with this round and all of the READMEs pass.

**Pull request merged**
